RACE_ETHNICITY_CATEGORIES = [
    "Alaska Native or Alaskan Native",
    "American Indian or Alaska Native",
    "Asian or Asian American",
    "Biracial, multiracial, or mixed race",
    "Black or African American",
    "Hispanic or Latino",
    "Middle Eastern or North African",
    "Native Hawaiian or Pacific Islander",
    "Indigenous",
    "White",
]

SEX_CATEGORIES = ["male", "female"]

SUPPORT_SYSTEM_OPTIONS = [
    "mother",
    "father",
    "sister",
    "brother",
    "child",
    "married partner",
    "non-married partner",
    "grandmother",
    "grandfather",
    "uncle",
    "aunt",
    "cousin",
    "friend",
    "work colleague",
    "mentor",
]

OCCUPATION_TITLES = [
    "Certified Nursing Assistant",
    "Medical Assistant",
    "Dental Hygienist",
    "Registered Nurse",
    "Dietitian",
    "Behavioral Health Counselor",
    "Nurse Practitioner",
    "Physician Assistant",
    "Dentist",
    "Pharmacist",
    "Physician (M.D. or D.O.)",
    "Psychiatrist",
    "Orthopedic Surgeon",
]

MIN_PRACTICE_AGE_BY_OCCUPATION = {
    "Certified Nursing Assistant": 18,
    "Medical Assistant": 18,
    "Dental Hygienist": 21,
    "Registered Nurse": 22,
    "Dietitian": 24,
    "Behavioral Health Counselor": 22,
    "Nurse Practitioner": 27,
    "Physician Assistant": 24,
    "Dentist": 28,
    "Pharmacist": 28,
    "Physician (M.D. or D.O.)": 28,
    "Psychiatrist": 30,
    "Orthopedic Surgeon": 31,
}

INCOME_BY_OCCUPATION = {
    "Registered Nurse": {"range": [66030, 135320]},
    "Nurse Practitioner": {"range": [94530, 165240]},
    "Medical Assistant": {"range": [30390, 51710]},
    "Certified Nursing Assistant": {"range": [28000, 45940]},
    "Physician (M.D. or D.O.)": {"range": [120000, 500000]},
    "Physician Assistant": {"range": [95000, 182000]},
    "Dentist": {"range": [79000, 220000]},
    "Dental Hygienist": {"range": [60100, 107640]},
    "Dietitian": {"range": [44140, 98830]},
    "Pharmacist": {"range": [89980, 168650]},
    "Behavioral Health Counselor": {"range": [34580, 89920]},
    "Psychiatrist": {"range": [75000, 350000]},
    "Orthopedic Surgeon": {"range": [150000, 600000]},
}

CLINICAL_PRIORITIES = [
    "maximizing patient load",
    "maximizing revenue",
    "active listening",
    "empathy",
    "evidence-based medical decision making",
    "EHR documentation",
    "shared-decision making",
    "research",
    "maximizing patient satisfaction",
    "reduced cognitive load",
    "improved medication and care plan adherence",
    "improved clinical physical-behavioral outcomes",
    "improved patient-provider relationships",
]

PERSONALITY_BY_OCCUPATION = {
    "Registered Nurse": "Agreeable, assertive, conscientious, and steady under pressure, with a strong practical orientation toward team-based care.",
    "Nurse Practitioner": "Collaborative, organized, and confident, with a balanced mix of autonomy and patient-centered communication.",
    "Medical Assistant": "Reliable, structured, and service-oriented, with a strong focus on efficient clinic flow and routine execution.",
    "Certified Nursing Assistant": "Warm, dependable, and relationship-oriented, with a high tolerance for repetitive support tasks.",
    "Physician (M.D. or D.O.)": "Analytical, decisive, and perfectionistic, with a strong preference for evidence-guided action in ambiguous cases.",
    "Physician Assistant": "Adaptable, pragmatic, and team-oriented, comfortable moving between independent action and collaboration.",
    "Dentist": "Detail-focused, methodical, and disciplined, with a strong preference for precision and predictable routines.",
    "Dental Hygienist": "Conscientious, communicative, and prevention-focused, with strong patient-education habits.",
    "Dietitian": "Cooperative, persistent, and coaching-oriented, with patience for behavior-change work.",
    "Pharmacist": "Highly responsible, careful, and informative, with strong attention to safety and reconciliation detail.",
    "Behavioral Health Counselor": "Empathic, reflective, and emotionally steady, with strong listening and rapport-building tendencies.",
    "Psychiatrist": "Thoughtful, observant, and measured, balancing diagnostic rigor with interpersonal sensitivity.",
    "Orthopedic Surgeon": "Confident, efficient, and action-oriented, with high tolerance for procedural intensity and decisive planning.",
}

US_STATES = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]
